general:
  name: PretrainedChordMixer
  seed: 42
  batch_size: 8
  max_epochs: 1
  log_interval: 100
  log_to_wandb: false

dataset:
  path: ${hydra:runtime.cwd}/data/variant_effect_prediction
  name: hg38.fa

dataloader:
  _target_: dataloader.PretrainedChordMixerDataLoader
  data_path: ${dataset.path}
  dataset_filename: ${dataset.name}
  batch_size: ${general.batch_size}
  mask_ratio: 0.15
  sequence_length: 500


model: 
  _target_: model.PretrainedChordMixer
  vocab_size: 4
  sequence_length: ${dataloader.sequence_length}
  encoder_track_size: 16
  decoder_track_size: 8
  hidden_size: 196
  mlp_dropout: 0
  layer_dropout: 0

loss: 
  _target_: torch.nn.NLLLoss
  ignore_index: 0

optimizer:
  _target_: torch.optim.Adam
  lr: 0.0001

trainer:
  _target_: trainer.PretrainedChordMixerTrainer
  log_interval: ${general.log_interval}

wandb: 
  entity: ravaghi
  project: PDT
  name: ${general.name}-L${dataloader.sequence_length}-MR${dataloader.mask_ratio}-LR${optimizer.lr}-BS${general.batch_size}

hydra:
  run:
    dir: ${hydra:runtime.cwd}/outputs
