_target_: models.chordmixer_finetuning.FineTunedChordMixer
model_path: ${hydra:runtime.cwd}/models/pcm-vl.pt
freeze: True
variable_length: ${dataset.variable_length}
n_class: ${dataset.n_class}
decoder_track_size: 16
decoder_hidden_size: 100
decoder_mlp_dropout: 0.2
decoder_layer_dropout: 0.2