_target_: models.chordmixer_pretraining.PretrainedChordMixer
vocab_size: 4
encoder_track_size: 16
encoder_hidden_size: 750
encoder_mlp_dropout: 0
encoder_layer_dropout: 0.1
decoder_track_size: 8
decoder_hidden_size: 600
decoder_mlp_dropout: 0.02
decoder_layer_dropout: 0.07
max_seq_len: 261943
variable_length: true
