_target_: models.chordmixer_finetuning.FineTunedChordMixer
model_path: ${hydra:runtime.cwd}/models/pcm-vl.pt
freeze: True
variable_length: ${dataset.variable_length}
n_class: ${dataset.n_class}
decoder_track_size: 4
decoder_hidden_size: 200
decoder_mlp_dropout: 0.0
decoder_layer_dropout: 0.3