_target_: models.chordmixer_finetuning.FineTunedChordMixer
model_path: ${hydra:runtime.cwd}/models/pcm-cl-1000-human.pt
freeze: True
variable_length: ${dataset.variable_length}
n_class: ${dataset.n_class}
decoder_track_size: 8
decoder_hidden_size: 140
decoder_mlp_dropout: 0.0
decoder_layer_dropout: 0.0