_target_: models.chordmixer_finetuning.FineTunedChordMixer
model_path: ${hydra:runtime.cwd}/models/23Feb2023_044225-TestAuc-0.8239-TestAcc-0.4263.pt
hidden_size: 300
freeze: True
variable_length: ${dataset.variable_length}
n_class: ${dataset.n_class}
