_target_: models.chordmixer_finetuning.FineTunedChordMixer
model_path: /cluster/home/mahdih/PretrainedChordMixer/logs/checkpoints/PretrainedChordMixerCL1000/29Mar2023_151150-TestAuc-0.5783-TestAcc-0.3333.pt
freeze: True
variable_length: ${dataset.variable_length}
n_class: ${dataset.n_class}
decoder_track_size: 16
decoder_hidden_size: 196
decoder_mlp_dropout: 0.0
decoder_layer_dropout: 0.0