_target_: models.poolformer.Poolformer
vocab_size: ${dataset.vocab_size}
embedding_size: 128
num_layers: 2
const_vector_length: 25000
n_class: ${dataset.n_class}
pooling: flatten
device_id: ${general.device_id}