_target_: models.transformer.Transformer
vocab_size: ${dataset.vocab_size}
embedding_size: 128
num_heads: 2
num_layers: 1
const_vector_length: 25000
n_class: ${dataset.n_class}
pooling: flatten
device_id: ${general.device_id}
