type: PlantDeepSEA
name: SetariaItalica
path: ${hydra:runtime.cwd}/../data/plant_deepsea/setaria_italica
train_data: setaria_italica_train.csv
val_data: setaria_italica_val.csv
test_data: setaria_italica_test.csv
variable_length: false
max_seq_len: 1000
vocab_size: 20
n_class: 9 