type: PlantOcrPrediction
name: SetariaItalica
path: ${hydra:runtime.cwd}/data/plant_ocr_prediction/setaria_italica
train_data: setaria_italica_train.parquet
val_data: setaria_italica_val.parquet
test_data: setaria_italica_test.parquet
variable_length: false
max_seq_len: 1000
vocab_size: 20
n_class: 9 