type: PlantDeepSEA
name: OryzaSativaMH
path: ${hydra:runtime.cwd}/../data/plant_deepsea/oryza_sativa_mh
train_data: oryza_sativa_mh_train.csv
val_data: oryza_sativa_mh_val.csv
test_data: oryza_sativa_mh_test.csv
variable_length: false
max_seq_len: 1000
vocab_size: 20
n_class: 15