type: PlantOcrPrediction
name: OryzaSativaZS
path: ${hydra:runtime.cwd}/data/plant_ocr_prediction/oryza_sativa_zs
train_data: oryza_sativa_zs_train.parquet
val_data: oryza_sativa_zs_val.parquet
test_data: oryza_sativa_zs_test.parquet
variable_length: false
max_seq_len: 1000
vocab_size: 20
n_class: 15