type: PlantDeepSEA
name: SorghumBicolor
path: ${hydra:runtime.cwd}/../data/plant_deepsea/sorghum_bicolor
train_data: sorghum_bicolor_train.csv
val_data: sorghum_bicolor_val.csv
test_data: sorghum_bicolor_test.csv
variable_length: false
max_seq_len: 1000
vocab_size: 20
n_class: 14