type: PlantDeepSEA
name: ArabidopsisThaliana
path: ${hydra:runtime.cwd}/../data/plant_deepsea/arabidopsis_thaliana
train_data: arabidopsis_thaliana_train.csv
val_data: arabidopsis_thaliana_val.csv
test_data: arabidopsis_thaliana_test.csv
variable_length: false
max_seq_len: 1000
vocab_size: 20
n_class: 19 