type: PlantOcrPrediction
name: BrachypodiumDistachyon
path: ${hydra:runtime.cwd}/data/plant_ocr_prediction/brachypodium_distachyon
train_data: brachypodium_distachyon_train.parquet
val_data: brachypodium_distachyon_val.parquet
test_data: brachypodium_distachyon_test.parquet
variable_length: false
max_seq_len: 1000
vocab_size: 20
n_class: 9 