type: PlantOcrPrediction
name: SorghumBicolor
path: ${hydra:runtime.cwd}/data/plant_ocr_prediction/sorghum_bicolor
train_data: sorghum_bicolor_train.parquet
val_data: sorghum_bicolor_val.parquet
test_data: sorghum_bicolor_test.parquet
variable_length: false
max_seq_len: 1000
vocab_size: 20
n_class: 14