type: TaxonomyClassification
name: SusVsBos
path: ${hydra:runtime.cwd}/../data/taxonomy_classification/sus_bos
train_data: sus_bos_train.csv
val_data: sus_bos_val.csv
test_data: sus_bos_test.csv
variable_length: true
max_seq_len: 447010
vocab_size: 20
n_class: 2