type: VariantEffectPrediction
name: Human
path: ${hydra:runtime.cwd}/../data/variant_effect_prediction
train_data: variant_effect_prediction_train.csv
val_data: variant_effect_prediction_val.csv
test_data: variant_effect_prediction_test.csv
variable_length: false
max_seq_len: 2000
vocab_size: 20
n_class: 49