type: PlantVariantEffectPrediction
name: BrachypodiumDistachyon
path: ${hydra:runtime.cwd}/data/variant_effect_prediction/plant/brachypodium_distachyon
train_data: brachypodium_distachyon_train.csv
val_data: brachypodium_distachyon_val.csv
test_data: brachypodium_distachyon_test.csv
variable_length: false
max_seq_len: 1000
vocab_size: 20
n_class: 9 