defaults:
  - _self_
  - model: chordmixer_pretraining
  - loss: nllloss
  - dataloader: chordmixer_pretraining
  - trainer: chordmixer_pretraining

dataset:
  path: ${hydra:runtime.cwd}/data/variant_effect_prediction/human
  type: pretraining
  name: hg38.fa
  train_data: label811_49_train.csv
  val_data: label811_49_val.csv
  test_data: label811_49_test.csv

optimizer:
  _target_: torch.optim.Adam
  lr: 0.0003

wandb: 
  entity: ravaghi
  project: PretrainedChordMixer
  name: ${general.name}

general:
  name: PretrainedChordMixer
  seed: 42
  batch_size: 64
  max_epochs: 30
  log_to_wandb: true
  use_multi_gpu: true
  save_dir: ${hydra:runtime.cwd}/logs/checkpoints/${general.name}

hydra:
  run:
    dir: ${hydra:runtime.cwd}/logs/hydra/outputs
