defaults:
  - _self_
  - model: chordmixer_pretraining_cl
  - loss: nllloss
  - dataloader: chordmixer_pretraining_cl_plant
  - trainer: chordmixer_pretraining

dataset:
  path: ${hydra:runtime.cwd}/data/plant_ocr_prediction

optimizer:
  _target_: torch.optim.Adam
  lr: 0.0005

wandb: 
  entity: ravaghi
  project: PretrainedChordMixer
  name: ${general.name}

general:
  name: PretrainedChordMixerCL1000Plant
  seed: 42
  batch_size: 416
  max_epochs: 50
  log_to_wandb: false
  use_multi_gpu: false
  use_scheduler: false
  save_dir: ${hydra:runtime.cwd}/logs/checkpoints/${general.name}

hydra:
  run:
    dir: ${hydra:runtime.cwd}/logs/hydra/outputs
