defaults:
  - _self_
  - model: chordmixer
  - loss: cross_entropy
  - optimizer: adam
  - dataset: ???
  - dataloader: chordmixer
  - trainer: chordmixer
  - wandb: wandb

general:
  name: ChordMixer
  seed: 42
  device_id: 0
  batch_size: 2
  max_epochs: 30
  log_to_wandb: false
  use_multi_gpu: false
  save_dir: ${hydra:runtime.cwd}/logs/checkpoints/${general.name}

hydra:
  run:
    dir: ${hydra:runtime.cwd}/logs/hydra/outputs
