defaults:
  - _self_
  - model: chordmixer_pretraining
  - loss: nllloss
  - dataloader: chordmixer_pretraining
  - trainer: chordmixer_pretraining

dataset:
  path: ${hydra:runtime.cwd}/data/variant_effect_prediction/human
  name: hg38.fa
  type: pretraining

optimizer:
  _target_: torch.optim.Adam
  lr: 0.0003

wandb: 
  entity: ravaghi
  project: PretrainedChordMixer
  name: ${general.name}

general:
  name: PretrainedChordMixer
  seed: 42
  batch_size: 32
  max_epochs: 10
  log_interval: 100
  log_to_wandb: false
  use_multi_gpu: false
  save_dir: ${hydra:runtime.cwd}/logs/checkpoints/${general.name}

hydra:
  run:
    dir: ${hydra:runtime.cwd}/logs/hydra/outputs
