defaults:
  - _self_
  - model: cnn
  - loss: cross_entropy
  - dataset: ???
  - dataloader: cnn
  - trainer: cnn
  - wandb: wandb

optimizer:
  _target_: torch.optim.SGD
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.005

general:
  name: CNN
  seed: 42
  device_id: 0
  batch_size: 50
  max_epochs: 30
  log_to_wandb: false
  use_multi_gpu: false
  save_dir: ${hydra:runtime.cwd}/logs/checkpoints/${general.name}

hydra:
  run:
    dir: ${hydra:runtime.cwd}/logs/hydra/outputs
