defaults:
  - _self_
  - model: cnn
  - loss: cross_entropy
  - dataset: ???
  - dataloader: cnn
  - trainer: cnn
  - wandb: wandb

optimizer:
  _target_: torch.optim.Adam
  lr: 0.001

general:
  name: CNN
  seed: 42
  device_id: 0
  batch_size: 50
  max_epochs: 30
  log_to_wandb: false
  use_multi_gpu: false
  save_dir: ${hydra:runtime.cwd}/logs/checkpoints/${general.name}/${dataset.type}/${dataset.name}

hydra:
  run:
    dir: ${hydra:runtime.cwd}/logs/hydra/outputs
