defaults:
  - _self_
  - model: cnn
  - loss: cross_entropy
  - optimizer: sgd
  - dataset: ???
  - dataloader: cnn
  - trainer: cnn
  - wandb: wandb

general:
  name: CNN
  seed: 42
  device_id: 0
  batch_size: 50
  max_epochs: 30
  log_to_wandb: false
  use_multi_gpu: false

hydra:
  run:
    dir: ${hydra:runtime.cwd}/../outputs
