defaults:
  - _self_
  - model: cnn
  - loss: binary_cross_entropy_with_logits
  - dataset: ???
  - dataloader: cnn
  - trainer: cnn
  - wandb: wandb

optimizer:
  _target_: torch.optim.SGD
  lr: 0.001
  weight_decay: 1e-6
  momentum: 0.9

general:
  name: CNN
  seed: 42
  device_id: 0
  batch_size: 50
  max_epochs: 30
  log_to_wandb: true
  use_multi_gpu: false
  use_scheduler: false
  save_dir: ${hydra:runtime.cwd}/logs/checkpoints/${general.name}/${dataset.type}/${dataset.name}

hydra:
  run:
    dir: ${hydra:runtime.cwd}/logs/hydra/outputs
