defaults:
  - _self_
  - model: kegru
  - loss: binary_cross_entropy
  - optimizer: kegru_adam
  - dataset: ???
  - dataloader: kegru
  - trainer: kegru
  - wandb: wandb

general:
  name: KeGRU
  seed: 42
  device_id: 0
  batch_size: 100
  max_epochs: 30
  log_to_wandb: false
  use_multi_gpu: false
  save_dir: ${hydra:runtime.cwd}/logs/checkpoints/${general.name}

hydra:
  run:
    dir: ${hydra:runtime.cwd}/logs/hydra/outputs
