defaults:
  - _self_
  - model: kegru
  - loss: cross_entropy
  - dataset: ???
  - dataloader: kegru
  - trainer: kegru
  - wandb: wandb

optimizer:
  _target_: torch.optim.Adam
  lr: 0.005
  weight_decay: 1e-5

general:
  name: KeGRU
  seed: 42
  device_id: 0
  batch_size: 100
  max_epochs: 30
  log_to_wandb: true
  use_multi_gpu: false
  save_dir: ${hydra:runtime.cwd}/logs/checkpoints/${general.name}

hydra:
  run:
    dir: ${hydra:runtime.cwd}/logs/hydra/outputs
