defaults:
  - _self_
  - model: linformer
  - loss: cross_entropy
  - optimizer: linformer_adam
  - dataset: ???
  - dataloader: linformer
  - trainer: linformer
  - wandb: wandb

general:
  name: Linformer
  seed: 42
  device_id: 0
  batch_size: 4
  max_epochs: 30
  log_to_wandb: false
  use_multi_gpu: false

hydra:
  run:
    dir: ${hydra:runtime.cwd}/outputs
