defaults:
  - _self_
  - model: poolformer
  - loss: cross_entropy
  - optimizer: poolformer_adam
  - dataset: ???
  - dataloader: poolformer
  - trainer: poolformer
  - wandb: wandb

general:
  name: Poolformer
  seed: 42
  device_id: 0
  batch_size: 4
  max_epochs: 30
  log_to_wandb: false
  use_multi_gpu: false

hydra:
  run:
    dir: ${hydra:runtime.cwd}/outputs
