general:
  name: PretrainedChordMixer
  seed: 42
  batch_size: 32
  max_epochs: 10
  log_interval: 20
  log_to_wandb: true
  use_multi_gpu: true

dataset:
  path: ${hydra:runtime.cwd}/data/variant_effect_prediction
  name: hg38.fa
  type: pretraining

dataloader:
  _target_: dataloaders.pretraining.PretrainedChordMixerDataLoader
  data_path: ${dataset.path}
  dataset_filename: ${dataset.name}
  batch_size: ${general.batch_size}
  mask_ratio: 0.15
  sequence_length: 10_000

model: 
  _target_: models.pretraining.PretrainedChordMixer
  vocab_size: 5
  n_blocks: 20
  encoder_track_size: 16
  decoder_track_size: 8
  encoder_prelinear_out_features: 1000
  decoder_prelinear_in_features: ${model.encoder_prelinear_out_features}
  decoder_prelinear_out_features: 500
  hidden_size: 196
  mlp_dropout: 0
  layer_dropout: 0

loss: 
  _target_: torch.nn.NLLLoss
  ignore_index: 0

optimizer:
  _target_: torch.optim.Adam
  lr: 0.0003

trainer:
  _target_: trainers.pretraining.PretrainedChordMixerTrainer
  log_interval: ${general.log_interval}
  log_to_wandb: ${general.log_to_wandb}

wandb: 
  entity: ravaghi
  project: PDT
  name: ${general.name}

hydra:
  run:
    dir: ${hydra:runtime.cwd}/outputs
