general:
  name: PretrainedChordMixer
  seed: 42
  device_id: 0
  batch_size: 30
  max_epochs: 10

dataset:
  path: ${hydra:runtime.cwd}/data/variant_effect_prediction
  name: hg38.fa

dataloader:
  _target_: dataloader.PretrainedChordMixerDataLoader
  data_path: ${dataset.path}
  dataset_filename: ${dataset.name}
  batch_size: ${general.batch_size}
  mask_ratio: 0.15
  sequence_length: 500


model: 
  _target_: model.PretrainedChordMixer
  sequence_length: ${dataloader.sequence_length}
  encoder_track_size: 16
  decoder_track_size: 8
  hidden_size: 196
  mlp_dropout: 0
  layer_dropout: 0

loss: 
  _target_: torch.nn.CrossEntropyLoss
  reduction: mean

optimizer:
  _target_: torch.optim.Adam
  lr: 0.0001

trainer:
  _target_: trainer.PretrainedChordMixerTrainer

wandb: 
  entity: ravaghi
  project: PDT
  name: ${general.name}

hydra:
  run:
    dir: ${hydra:runtime.cwd}/outputs
