defaults:
  - _self_
  - model: reformer
  - loss: cross_entropy
  - optimizer: reformer_adam
  - dataset: ???
  - dataloader: reformer
  - trainer: reformer
  - wandb: wandb

general:
  name: Reformer
  seed: 42
  device_id: 0
  batch_size: 4
  max_epochs: 30
  log_to_wandb: false
  use_multi_gpu: false
  save_dir: ${hydra:runtime.cwd}/logs/checkpoints/${general.name}

hydra:
  run:
    dir: ${hydra:runtime.cwd}/logs/hydra/outputs
