defaults:
  - _self_
  - model: transformer
  - loss: cross_entropy
  - optimizer: transformer_adam
  - dataset: ???
  - dataloader: transformer
  - trainer: transformer
  - wandb: wandb

general:
  name: Transformer
  seed: 42
  device_id: 0
  batch_size: 4
  max_epochs: 30
  log_to_wandb: false
  use_multi_gpu: false
  save_dir: ${hydra:runtime.cwd}/logs/checkpoints/${general.name}

hydra:
  run:
    dir: ${hydra:runtime.cwd}/logs/hydra/outputs
